### PR TITLE
Fix unexpected behavior with hashtable

### LINKED ISSUE #46: Unexpected behavior when using Property Query with Dictionary
Image

Expected output is following.

```
query>:
Key Name Value
```

### PR DESCRIPTION
**Pull request by krymtkts**
Fix #46

### CODE REVIEW

File: src/pocof/Library.fs [hunk 1]
```diff
@@ -151,13 +151,21 @@ type SelectPocofCommand() =
...
 
         properties <-
             __.InputObject
-            |> Seq.collect (fun o -> o.Properties |> Seq.cast<PSPropertyInfo>)
-            |> Seq.fold (fun acc m -> acc.Add(m.Name)) properties
+            |> Seq.collect (fun o ->
+                match o.BaseObject with
+                | :? IDictionary as dct ->
+                    Seq.cast<DictionaryEntry> dct
+                    |> Seq.head
```
Comment (krymtkts) [inline src/pocof/Library.fs:163]: Check if it works when the hashtable is empty.

**Review by krymtkts — COMMENTED** [review]
works fine.
